//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using Framework.Data.Model;

namespace Framework.Data.Context
{
    public partial class AppContext : DbContext
    {
        public AppContext()
            : base("name=AppContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		modelBuilder.Conventions.Remove<IncludeMetadataConvention>();	 
        }
    
    	public virtual void Commit()
        {
            base.SaveChanges();
        }
    
        public DbSet<AccessToken> AccessTokens { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<ClientScope> ClientScopes { get; set; }
        public DbSet<Scope> Scopes { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
    }
}
