//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Framework.Data.Model
{
    [Table("AccessToken")]
    public partial class AccessToken
    {
    	[Key]  
        public string Token { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime ExpirationDateUtc { get; set; }
    	[ForeignKey("Client")]
        public int ClientID { get; set; }
    
    	public virtual Client Client { get; set; }
    }
}
