//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Framework.Data.Model
{
    [Table("Client")]
    public partial class Client
    {
        public Client()
        {
            this.AccessTokens = new HashSet<AccessToken>();
            this.ClientScopes = new HashSet<ClientScope>();
        }
    
    	[Key]  
        public int ID { get; set; }
        public string ClientIdentifier { get; set; }
        public string ClientSecret { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
    	public virtual ICollection<AccessToken> AccessTokens { get; set; }
    	public virtual ICollection<ClientScope> ClientScopes { get; set; }
    }
}
