//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Framework.Data.Model
{
    [Table("ErrorLog")]
    public partial class ErrorLog
    {
    	[Key]  
        public int LogId { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public string HelpLink { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime TimeOccured { get; set; }
    }
}
