//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Framework.Data.Model
{
    [Table("Scope")]
    public partial class Scope
    {
        public Scope()
        {
            this.ClientScopes = new HashSet<ClientScope>();
        }
    
    	[Key]  
        public int ID { get; set; }
        public string Name { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Description { get; set; }
    
    	public virtual ICollection<ClientScope> ClientScopes { get; set; }
    }
}
