//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Framework.Data.Model
{
    [Table("UserProfile")]
    public partial class UserProfile
    {
    	[Key]  
        public int UserId { get; set; }
        public string UserName { get; set; }
        public bool IsActive { get; set; }
    }
}
