//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;

namespace Framework.Data.Repository
{
    public partial interface IAccessTokenRepository : IRepository<AccessToken>
    {
    }
    
    public partial class AccessTokenRepository : RepositoryBase<AccessToken>, IAccessTokenRepository
    {
        public AccessTokenRepository(IDatabaseFactory databaseFactory) : base(databaseFactory) { }
    }
     
}
