//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;

namespace Framework.Data.Repository
{
    public partial interface IClientRepository : IRepository<Client>
    {
    }
    
    public partial class ClientRepository : RepositoryBase<Client>, IClientRepository
    {
        public ClientRepository(IDatabaseFactory databaseFactory) : base(databaseFactory) { }
    }
     
}
