//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;

namespace Framework.Data.Repository
{
    public partial interface IClientScopeRepository : IRepository<ClientScope>
    {
    }
    
    public partial class ClientScopeRepository : RepositoryBase<ClientScope>, IClientScopeRepository
    {
        public ClientScopeRepository(IDatabaseFactory databaseFactory) : base(databaseFactory) { }
    }
     
}
