//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;

namespace Framework.Data.Repository
{
    public partial interface IErrorLogRepository : IRepository<ErrorLog>
    {
    }
    
    public partial class ErrorLogRepository : RepositoryBase<ErrorLog>, IErrorLogRepository
    {
        public ErrorLogRepository(IDatabaseFactory databaseFactory) : base(databaseFactory) { }
    }
     
}
