//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;
using Framework.Data.Repository;

namespace Framework.Data.Service
{
    public partial interface IAccessTokenService
    {
    }
    
    public partial class AccessTokenService : IAccessTokenService
    {
        #region Dependency Injuction
    
        private readonly IAccessTokenRepository _accessTokenRepository;
        private readonly IUnitOfWork _unitOfWork;
    
        public AccessTokenService(IAccessTokenRepository accessTokenRepository, IUnitOfWork unitOfWork)
        {
            this._accessTokenRepository = accessTokenRepository;
            this._unitOfWork = unitOfWork;
        }
    
        #endregion
    } 
}
