//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;
using Framework.Data.Repository;

namespace Framework.Data.Service
{
    public partial interface IClientService
    {
    }
    
    public partial class ClientService : IClientService
    {
        #region Dependency Injuction
    
        private readonly IClientRepository _clientRepository;
        private readonly IUnitOfWork _unitOfWork;
    
        public ClientService(IClientRepository clientRepository, IUnitOfWork unitOfWork)
        {
            this._clientRepository = clientRepository;
            this._unitOfWork = unitOfWork;
        }
    
        #endregion
    } 
}
