//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;
using Framework.Data.Repository;

namespace Framework.Data.Service
{
    public partial interface IClientScopeService
    {
    }
    
    public partial class ClientScopeService : IClientScopeService
    {
        #region Dependency Injuction
    
        private readonly IClientScopeRepository _clientScopeRepository;
        private readonly IUnitOfWork _unitOfWork;
    
        public ClientScopeService(IClientScopeRepository clientScopeRepository, IUnitOfWork unitOfWork)
        {
            this._clientScopeRepository = clientScopeRepository;
            this._unitOfWork = unitOfWork;
        }
    
        #endregion
    } 
}
