//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;
using Framework.Data.Repository;

namespace Framework.Data.Service
{
    public partial interface IErrorLogService
    {
    }
    
    public partial class ErrorLogService : IErrorLogService
    {
        #region Dependency Injuction
    
        private readonly IErrorLogRepository _errorLogRepository;
        private readonly IUnitOfWork _unitOfWork;
    
        public ErrorLogService(IErrorLogRepository errorLogRepository, IUnitOfWork unitOfWork)
        {
            this._errorLogRepository = errorLogRepository;
            this._unitOfWork = unitOfWork;
        }
    
        #endregion
    } 
}
