//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;
using Framework.Data.Repository;

namespace Framework.Data.Service
{
    public partial interface IScopeService
    {
    }
    
    public partial class ScopeService : IScopeService
    {
        #region Dependency Injuction
    
        private readonly IScopeRepository _scopeRepository;
        private readonly IUnitOfWork _unitOfWork;
    
        public ScopeService(IScopeRepository scopeRepository, IUnitOfWork unitOfWork)
        {
            this._scopeRepository = scopeRepository;
            this._unitOfWork = unitOfWork;
        }
    
        #endregion
    } 
}
