//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Data.Model;
using Framework.Data.Infrastructure;
using Framework.Data.Repository;

namespace Framework.Data.Service
{
    public partial interface IUserProfileService
    {
    }
    
    public partial class UserProfileService : IUserProfileService
    {
        #region Dependency Injuction
    
        private readonly IUserProfileRepository _userProfileRepository;
        private readonly IUnitOfWork _unitOfWork;
    
        public UserProfileService(IUserProfileRepository userProfileRepository, IUnitOfWork unitOfWork)
        {
            this._userProfileRepository = userProfileRepository;
            this._unitOfWork = unitOfWork;
        }
    
        #endregion
    } 
}
